export default {
  testEnvironment: "node",
  clearMocks: true,
  verbose: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  collectCoverageFrom: [
    "src/**/*.js",
    "!src/*.js",
    "!src/**/*.test.js",
    "!src/modules/**/*.schema.js",
    "!src/modules/**/dto/**",
    "!src/modules/**/response/**",
    "!src/modules/health/**",
    "!src/modules/sockets/*.js",
    "!src/modules/sockets/events/**",
    "!src/modules/shared/database/**",
    "!src/modules/shared/erros/**",
    "!src/modules/shared/logger/**",
  ],
};
