import { jest } from '@jest/globals';
import bcrypt from 'bcryptjs';
import PlayerService from '../../../src/modules/player/player.service.js';
import PlayerRepository from '../../../src/modules/player/player.repository.js';

const mockSchema = {}; 
process.env.JWT_SECRET = 'segredinho_para_testes';

describe('player.service.js - Create', () => {
    let playerService;

    // ARRANGE
    const baseValidData = {
        username: 'davi_uno',
        age: 20,
        email: 'davi@uno.com',
        password: 'senha_secreta'
    };

    beforeEach(() => {
        jest.clearAllMocks();

        // Arrange
        playerService = new PlayerService(mockSchema);

        // Disable logs to avoid polluting the terminal during the tests.
        jest.spyOn(playerService.log, 'info').mockImplementation(() => {});
        jest.spyOn(playerService.log, 'warn').mockImplementation(() => {});
    });

    test('should successfully create a player (Happy Path)', async () => {

        // Here mock the service. 
        jest.spyOn(PlayerRepository.prototype, 'getByEmail').mockResolvedValue(null);
        jest.spyOn(PlayerRepository.prototype, 'getByUsername').mockResolvedValue(null);
        
        // Fake password hash to keep the test fast (KISS)
        jest.spyOn(bcrypt, 'hash').mockResolvedValue('senha_criptografada');
        
        // Mock database creation response
        jest.spyOn(PlayerRepository.prototype, 'create').mockResolvedValue({
        _id: '12345',
        username: baseValidData.username,
        email: baseValidData.email,
        password: 'senha_criptografada'
        });

        // ACT
        const result = await playerService.create(baseValidData);

        // ASSERT
        // Ensure the service returns the ID and name generated by the mock
        expect(result._id).toBe('12345'); 
        expect(result.username).toBe('davi_uno');
        
        // Ensure the password isn't stored in plain text (Secure by Default)
        expect(result.password).toBe('senha_criptografada');
    });

    test('should throw an error when email already exists', async () => {
        
        // ARRANGE
        jest.spyOn(PlayerRepository.prototype, 'getByEmail').mockResolvedValue(baseValidData.email);

        // ACT & ASSERT
        await expect(playerService.create(baseValidData))
        .rejects
        .toThrow("Email already exists"); // Jest verifies this specific error message
    });

    test('should throw an error when username already exists', async () => {

        // ARRANGE
        jest.spyOn(PlayerRepository.prototype, 'getByEmail').mockResolvedValue(null);
        jest.spyOn(PlayerRepository.prototype, 'getByUsername').mockResolvedValue(baseValidData.username);
    
        // ACT & ASSERT
        await expect(playerService.create(baseValidData))
        .rejects
        .toThrow("Username already exists");
    });
});

describe('player.service.js - Read (getById)', () => {

    let playerService;
    const playerId = '12345';

    const existingPlayer = { 
        _id: playerId, 
        username: 'davi_uno',
        email: 'davi@teste.com' 
    };

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should return a player when id exists (Happy Path)', async () => {
        // ARRANGE
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(existingPlayer);

        // ACT
        const result = await playerService.getById(playerId);

        // ASSERT
        expect(result).toEqual(existingPlayer);
        expect(result._id).toBe(playerId);
    });

    test('should throw an error when player id is not found', async () => {
        // ARRANGE
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(null);

        // ACT & ASSERT
        await expect(playerService.getById(playerId))
            .rejects
            .toThrow("Player not found");
    });
});

describe('player.service.js - Read (getAllByIds)', () => {
    let playerService;

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should return players matching the provided ids (Happy Path)', async () => {
        
        const ids = ['1', '2', '3'];
        const mockPlayers = [
            { _id: '1', username: 'davi_uno' },
            { _id: '2', username: 'gezonel' }
        ];

        const repositorySpy = jest
            .spyOn(PlayerRepository.prototype, 'getAllByIds')
            .mockResolvedValue(mockPlayers);

        const result = await playerService.getAllByIds(ids);

        expect(repositorySpy).toHaveBeenCalledWith(ids);
        expect(result).toEqual(mockPlayers);
        expect(result).toHaveLength(2);
    });
});

describe('player.service.js - Read (getByUsername)', () => {

    let playerService;
    const username = 'davi_uno';

    const existingPlayer = { 
        _id: '1', 
        username: username, 
        email: 'davi@teste.com' 
    };

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should return a player when username exists (Happy Path)', async () => {
        
        jest.spyOn(PlayerRepository.prototype, 'getByUsername').mockResolvedValue(existingPlayer);

        const result = await playerService.getByUsername(username);

        expect(result).toEqual(existingPlayer);
        expect(result.username).toBe(username);
    });

    test('should throw an error when username is not found', async () => {

        jest.spyOn(PlayerRepository.prototype, 'getByUsername').mockResolvedValue(null);

        await expect(playerService.getByUsername(username))
            .rejects
            .toThrow("Player not found");
    });
});

describe('player.service.js - Read (getByToken)', () => {

    let playerService;
    const token = 'fake_jwt_token';
    const playerId = '12345';

    const existingPlayer = { 
        _id: playerId, 
        username: 'davi_uno' 
    };

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should return a player using decoded token id (Happy Path)', async () => {
        
        jest.spyOn(playerService.jwtCoder, 'decode').mockReturnValue({ id: playerId });
        jest.spyOn(playerService, 'getById').mockResolvedValue(existingPlayer);

        const result = await playerService.getByToken(token);

        expect(playerService.jwtCoder.decode).toHaveBeenCalledWith(token);
        expect(playerService.getById).toHaveBeenCalledWith(playerId);
        expect(result).toEqual(existingPlayer);
    });
});

describe('player.service.js - Read (getAll)', () => {
    let playerService;
    
    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should return a list of players (Happy Path)', async () => {

        const playerList = [
            { _id: '1', username: 'davi_uno' },
            { _id: '2', username: 'gezonel' }
        ];
        
        jest.spyOn(PlayerRepository.prototype, 'getAll').mockResolvedValue(playerList);

        const result = await playerService.getAll();

        expect(result).toHaveLength(2);
        expect(result).toEqual(playerList);
    });
});

describe("player.service.js - Update", () => {

    let playerService;
    const playerId = '12345';

    const existingPlayer = {
        _id: playerId,
        username: 'davi_uno',
        email: 'davi@teste.com',
        password: 'senha_hasheada'
    };

    const validUpdateData = {
        username: 'gezonel_mestre_uno',
        email: 'novo_email@teste.com'
    };

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
        jest.spyOn(playerService.log, 'info').mockImplementation(() => {});
        jest.spyOn(playerService.log, 'warn').mockImplementation(() => {});
    });

    test('should successfully update a player (Happy Path)', async () => {
        
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(existingPlayer);
        jest.spyOn(PlayerRepository.prototype, 'getByEmail').mockResolvedValue(null);

        const updatedPlayer = { ...existingPlayer, ...validUpdateData };
        jest.spyOn(PlayerRepository.prototype, 'update').mockResolvedValue(updatedPlayer);

        const result = await playerService.update(playerId, validUpdateData);

        expect(result.username).toBe(validUpdateData.username);
        expect(result.email).toBe(validUpdateData.email);
    });

    test('should throw an error if player to update is not found', async () => {
       
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(null);

        await expect(playerService.update(playerId, validUpdateData))
            .rejects
            .toThrow("Player not found");
    });

    test('should throw an error when trying to update to an already used email', async () => {
        
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(existingPlayer);
        jest.spyOn(PlayerRepository.prototype, 'getByEmail').mockResolvedValue(true);

        // ACT & ASSERT
        await expect(playerService.update(playerId, validUpdateData))
            .rejects
            .toThrow("Email already exists");
    });
})

describe('player.service.js - Delete', () => {
    let playerService;
    const playerDeleteId = '12345';

    const existingPlayer = { _id: playerDeleteId, username: 'davi_uno' };

    beforeEach(() => {
        jest.clearAllMocks();
        playerService = new PlayerService({});
    });

    test('should successfully delete a player (Happy Path)', async () => {
        
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(existingPlayer);
        jest.spyOn(PlayerRepository.prototype, 'deleteById').mockResolvedValue(true);

        const result = await playerService.deleteById(playerDeleteId);
        expect(result).toBe(true);
    });

    test('should throw an error if player to delete is not found', async () => {
        
        jest.spyOn(PlayerRepository.prototype, 'getById').mockResolvedValue(null);

        await expect(playerService.deleteById(playerDeleteId))
           .rejects
           .toThrow("Player not found");
    });
})